//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPlanningApplication.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryDefs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryDefs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcPlanningApplication.Models.QueryDefs", typeof(QueryDefs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM HaworthOrders.
        /// </summary>
        internal static string DeleteAllHaworthOrders {
            get {
                return ResourceManager.GetString("DeleteAllHaworthOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM HaworthSupplierDemands.
        /// </summary>
        internal static string DeleteAllHaworthSupplierDemands {
            get {
                return ResourceManager.GetString("DeleteAllHaworthSupplierDemands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBCC CHECKIDENT (~p0, RESEED, 0).
        /// </summary>
        internal static string ReSeedTable {
            get {
                return ResourceManager.GetString("ReSeedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, [brk_qty##1] AS brk_qty__1, [brk_qty##2] AS brk_qty__2, [brk_qty##3] AS brk_qty__3, [brk_qty##4] AS brk_qty__4, [brk_qty##5] AS brk_qty__5
        ///FROM coitem
        ///WHERE co_cust_num IN (~p0) AND stat = &apos;~p1&apos;.
        /// </summary>
        internal static string SelectCOItemByCustNumListAndStatus {
            get {
                return ResourceManager.GetString("SelectCOItemByCustNumListAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT co.co_num, coitem.co_line, coitem.co_release, coitem.item, coitem.qty_ordered, coitem.promise_date, coitem.co_release, coitem.due_date, co.cust_po
        ///  FROM co
        ///	INNER JOIN coitem ON co.co_num = coitem.co_num
        ///  WHERE co.cust_po IN (~p0) AND coitem.stat IN (&apos;O&apos;, &apos;F&apos;, &apos;C&apos;)
        ///  ORDER BY co_num ASC.
        /// </summary>
        internal static string SelectCustomerOrdersByPO {
            get {
                return ResourceManager.GetString("SelectCustomerOrdersByPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM HaworthSupplierDemands
        ///  WHERE OrderNumber = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectHaworthSupplierDemandsByOrderNo {
            get {
                return ResourceManager.GetString("SelectHaworthSupplierDemandsByOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC WTF_App.[dbo].[Rpt_JobPickListSp] @Job = &apos;~p0&apos;,
        ///		@Suffix = &apos;~p1&apos;,
        ///		@Item = NULL,
        ///		@Whse = &apos;MAIN&apos;,
        ///		@StartingOperNum = NULL,
        ///		@EndingOperNum = NULL,
        ///		@SortByLoc = 0,
        ///		@IncludeSerialNumbers = 1,
        ///		@ReprintPickListItems = 1,
        ///		@PostMaterialIssues = 0,
        ///		@PageBetweenOperations = 0,
        ///		@PrintSecondaryLocations = 1,
        ///		@ExtendByScrapFactor = 0,
        ///		@PrintBarCode = 0,
        ///		@DisplayHeader = 1,
        ///		@PMessageLanguage = 1033.
        /// </summary>
        internal static string SpJobPickListByJobAndSuffix {
            get {
                return ResourceManager.GetString("SpJobPickListByJobAndSuffix", resourceCulture);
            }
        }
    }
}
