//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPlanningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobmatl
    {
        public string job { get; set; }
        public short suffix { get; set; }
        public int oper_num { get; set; }
        public short sequence { get; set; }
        public string matl_type { get; set; }
        public string item { get; set; }
        public Nullable<decimal> matl_qty { get; set; }
        public string units { get; set; }
        public decimal cost { get; set; }
        public Nullable<decimal> qty_issued { get; set; }
        public Nullable<decimal> a_cost { get; set; }
        public string ref_type { get; set; }
        public string ref_num { get; set; }
        public Nullable<short> ref_line_suf { get; set; }
        public Nullable<short> ref_release { get; set; }
        public Nullable<decimal> po_unit_cost { get; set; }
        public Nullable<System.DateTime> effect_date { get; set; }
        public Nullable<System.DateTime> obs_date { get; set; }
        public Nullable<decimal> scrap_fact { get; set; }
        public Nullable<decimal> qty_var { get; set; }
        public Nullable<decimal> fixovhd_t { get; set; }
        public Nullable<decimal> varovhd_t { get; set; }
        public string feature { get; set; }
        public Nullable<decimal> probable { get; set; }
        public string opt_code { get; set; }
        public Nullable<decimal> inc_price { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public Nullable<short> bom_seq { get; set; }
        public Nullable<decimal> matl_qty_conv { get; set; }
        public string u_m { get; set; }
        public Nullable<decimal> inc_price_conv { get; set; }
        public Nullable<decimal> cost_conv { get; set; }
        public Nullable<byte> backflush { get; set; }
        public string bflush_loc { get; set; }
        public Nullable<decimal> fmatlovhd { get; set; }
        public Nullable<decimal> vmatlovhd { get; set; }
        public decimal matl_cost { get; set; }
        public decimal lbr_cost { get; set; }
        public decimal fovhd_cost { get; set; }
        public decimal vovhd_cost { get; set; }
        public decimal out_cost { get; set; }
        public Nullable<decimal> a_matl_cost { get; set; }
        public Nullable<decimal> a_lbr_cost { get; set; }
        public Nullable<decimal> a_fovhd_cost { get; set; }
        public Nullable<decimal> a_vovhd_cost { get; set; }
        public Nullable<decimal> a_out_cost { get; set; }
        public Nullable<decimal> matl_cost_conv { get; set; }
        public Nullable<decimal> lbr_cost_conv { get; set; }
        public Nullable<decimal> fovhd_cost_conv { get; set; }
        public Nullable<decimal> vovhd_cost_conv { get; set; }
        public Nullable<decimal> out_cost_conv { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public short alt_group { get; set; }
        public short alt_group_rank { get; set; }
        public Nullable<byte> planned_alternate { get; set; }
        public Nullable<short> new_sequence { get; set; }
        public string manufacturer_id { get; set; }
        public string manufacturer_item { get; set; }
        public string uf_pref_type { get; set; }
    }
}
