//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPlanningApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SytelineDbEntities : DbContext
    {
        public SytelineDbEntities()
            : base("name=SytelineDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coitem> coitems { get; set; }
        public virtual DbSet<jobmatl> jobmatls { get; set; }
        public virtual DbSet<co> coes { get; set; }
    }
}
